language: ruby
sudo: false
before_install:
  - gem update --system
  - gem install bundler

matrix:
  include:
    - rvm: 2.5.0
      script: bundle exec rake rubocop # ONLY lint once, first
    - rvm: 2.1
    - rvm: 2.2.9
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.0
      env:
        - JRUBY_OPTS="--debug"
    - rvm: jruby-9.1.16.0
      env:
        - JRUBY_OPTS="--debug"
